// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metadata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReplayJob = `-- name: CancelReplayJob :one
UPDATE replay_jobs
SET status = 'canceled', canceled_at = $2
WHERE id = $1
RETURNING id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
`

type CancelReplayJobParams struct {
	ID         string             `json:"id"`
	CanceledAt pgtype.Timestamptz `json:"canceled_at"`
}

type CancelReplayJobRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) CancelReplayJob(ctx context.Context, arg CancelReplayJobParams) (CancelReplayJobRow, error) {
	row := q.db.QueryRow(ctx, cancelReplayJob, arg.ID, arg.CanceledAt)
	var i CancelReplayJobRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}

const completeReplayJobStatus = `-- name: CompleteReplayJobStatus :execrows
UPDATE replay_jobs
SET status = 'completed', completed_at = $2
WHERE id = $1
`

type CompleteReplayJobStatusParams struct {
	ID          string             `json:"id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteReplayJobStatus(ctx context.Context, arg CompleteReplayJobStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeReplayJobStatus, arg.ID, arg.CompletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDataset = `-- name: CreateDataset :one
INSERT INTO datasets (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_at
`

type CreateDatasetParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, createDataset, arg.ID, arg.Name, arg.Description)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createEventFile = `-- name: CreateEventFile :one
INSERT INTO event_files (id, dataset_id, path, format, symbol, bytes, sha256, rows)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, dataset_id, path, format, symbol, bytes, created_at, sha256, rows
`

type CreateEventFileParams struct {
	ID        string `json:"id"`
	DatasetID string `json:"dataset_id"`
	Path      string `json:"path"`
	Format    string `json:"format"`
	Symbol    string `json:"symbol"`
	Bytes     int64  `json:"bytes"`
	Sha256    string `json:"sha256"`
	Rows      int64  `json:"rows"`
}

func (q *Queries) CreateEventFile(ctx context.Context, arg CreateEventFileParams) (EventFile, error) {
	row := q.db.QueryRow(ctx, createEventFile,
		arg.ID,
		arg.DatasetID,
		arg.Path,
		arg.Format,
		arg.Symbol,
		arg.Bytes,
		arg.Sha256,
		arg.Rows,
	)
	var i EventFile
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Path,
		&i.Format,
		&i.Symbol,
		&i.Bytes,
		&i.CreatedAt,
		&i.Sha256,
		&i.Rows,
	)
	return i, err
}

const createReplayJob = `-- name: CreateReplayJob :one
INSERT INTO replay_jobs (id, dataset_id, event_file_id, idempotency_key, symbol, speed, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
`

type CreateReplayJobParams struct {
	ID             string      `json:"id"`
	DatasetID      string      `json:"dataset_id"`
	EventFileID    string      `json:"event_file_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Symbol         string      `json:"symbol"`
	Speed          string      `json:"speed"`
	Status         string      `json:"status"`
}

type CreateReplayJobRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (CreateReplayJobRow, error) {
	row := q.db.QueryRow(ctx, createReplayJob,
		arg.ID,
		arg.DatasetID,
		arg.EventFileID,
		arg.IdempotencyKey,
		arg.Symbol,
		arg.Speed,
		arg.Status,
	)
	var i CreateReplayJobRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}

const createReplayMetric = `-- name: CreateReplayMetric :one
INSERT INTO replay_metrics (
    id, job_id, rows, events, malformed_events, sequence_gaps, duration_ns,
    rows_per_second, events_per_second, p95_latency_ns, peak_alloc_bytes,
    allocs_per_event, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, job_id, rows, events, malformed_events, sequence_gaps, duration_ns,
    rows_per_second, events_per_second, p95_latency_ns, peak_alloc_bytes,
    allocs_per_event, created_at
`

type CreateReplayMetricParams struct {
	ID              string             `json:"id"`
	JobID           string             `json:"job_id"`
	Rows            int64              `json:"rows"`
	Events          int64              `json:"events"`
	MalformedEvents int64              `json:"malformed_events"`
	SequenceGaps    int64              `json:"sequence_gaps"`
	DurationNs      int64              `json:"duration_ns"`
	RowsPerSecond   float64            `json:"rows_per_second"`
	EventsPerSecond float64            `json:"events_per_second"`
	P95LatencyNs    int64              `json:"p95_latency_ns"`
	PeakAllocBytes  int64              `json:"peak_alloc_bytes"`
	AllocsPerEvent  float64            `json:"allocs_per_event"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReplayMetric(ctx context.Context, arg CreateReplayMetricParams) (ReplayMetric, error) {
	row := q.db.QueryRow(ctx, createReplayMetric,
		arg.ID,
		arg.JobID,
		arg.Rows,
		arg.Events,
		arg.MalformedEvents,
		arg.SequenceGaps,
		arg.DurationNs,
		arg.RowsPerSecond,
		arg.EventsPerSecond,
		arg.P95LatencyNs,
		arg.PeakAllocBytes,
		arg.AllocsPerEvent,
		arg.CreatedAt,
	)
	var i ReplayMetric
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Rows,
		&i.Events,
		&i.MalformedEvents,
		&i.SequenceGaps,
		&i.DurationNs,
		&i.RowsPerSecond,
		&i.EventsPerSecond,
		&i.P95LatencyNs,
		&i.PeakAllocBytes,
		&i.AllocsPerEvent,
		&i.CreatedAt,
	)
	return i, err
}

const createValidationError = `-- name: CreateValidationError :one
INSERT INTO validation_errors (id, job_id, line, symbol, type, message, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, line, symbol, type, message, created_at
`

type CreateValidationErrorParams struct {
	ID        string             `json:"id"`
	JobID     string             `json:"job_id"`
	Line      int64              `json:"line"`
	Symbol    string             `json:"symbol"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateValidationError(ctx context.Context, arg CreateValidationErrorParams) (ValidationError, error) {
	row := q.db.QueryRow(ctx, createValidationError,
		arg.ID,
		arg.JobID,
		arg.Line,
		arg.Symbol,
		arg.Type,
		arg.Message,
		arg.CreatedAt,
	)
	var i ValidationError
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Line,
		&i.Symbol,
		&i.Type,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getDataset = `-- name: GetDataset :one
SELECT id, name, description, created_at
FROM datasets
WHERE id = $1
`

func (q *Queries) GetDataset(ctx context.Context, id string) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDataset, id)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getEventFile = `-- name: GetEventFile :one
SELECT id, dataset_id, path, format, symbol, bytes, created_at, sha256, rows
FROM event_files
WHERE id = $1
`

func (q *Queries) GetEventFile(ctx context.Context, id string) (EventFile, error) {
	row := q.db.QueryRow(ctx, getEventFile, id)
	var i EventFile
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Path,
		&i.Format,
		&i.Symbol,
		&i.Bytes,
		&i.CreatedAt,
		&i.Sha256,
		&i.Rows,
	)
	return i, err
}

const getReplayJob = `-- name: GetReplayJob :one
SELECT id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
FROM replay_jobs
WHERE id = $1
`

type GetReplayJobRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) GetReplayJob(ctx context.Context, id string) (GetReplayJobRow, error) {
	row := q.db.QueryRow(ctx, getReplayJob, id)
	var i GetReplayJobRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}

const getReplayJobByIdempotencyKey = `-- name: GetReplayJobByIdempotencyKey :one
SELECT id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
FROM replay_jobs
WHERE idempotency_key = $1
`

type GetReplayJobByIdempotencyKeyRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) GetReplayJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (GetReplayJobByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getReplayJobByIdempotencyKey, idempotencyKey)
	var i GetReplayJobByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}

const listDatasets = `-- name: ListDatasets :many
SELECT id, name, description, created_at
FROM datasets
ORDER BY created_at ASC
`

func (q *Queries) ListDatasets(ctx context.Context) ([]Dataset, error) {
	rows, err := q.db.Query(ctx, listDatasets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dataset
	for rows.Next() {
		var i Dataset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventFiles = `-- name: ListEventFiles :many
SELECT id, dataset_id, path, format, symbol, bytes, created_at, sha256, rows
FROM event_files
WHERE dataset_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventFiles(ctx context.Context, datasetID string) ([]EventFile, error) {
	rows, err := q.db.Query(ctx, listEventFiles, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventFile
	for rows.Next() {
		var i EventFile
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.Path,
			&i.Format,
			&i.Symbol,
			&i.Bytes,
			&i.CreatedAt,
			&i.Sha256,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayJobs = `-- name: ListReplayJobs :many
SELECT id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
FROM replay_jobs
ORDER BY created_at ASC
`

type ListReplayJobsRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) ListReplayJobs(ctx context.Context) ([]ListReplayJobsRow, error) {
	rows, err := q.db.Query(ctx, listReplayJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReplayJobsRow
	for rows.Next() {
		var i ListReplayJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.EventFileID,
			&i.IdempotencyKey,
			&i.Symbol,
			&i.Speed,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CheckpointLine,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplayMetrics = `-- name: ListReplayMetrics :many
SELECT id, job_id, rows, events, malformed_events, sequence_gaps, duration_ns,
    rows_per_second, events_per_second, p95_latency_ns, peak_alloc_bytes,
    allocs_per_event, created_at
FROM replay_metrics
WHERE job_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListReplayMetrics(ctx context.Context, jobID string) ([]ReplayMetric, error) {
	rows, err := q.db.Query(ctx, listReplayMetrics, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayMetric
	for rows.Next() {
		var i ReplayMetric
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Rows,
			&i.Events,
			&i.MalformedEvents,
			&i.SequenceGaps,
			&i.DurationNs,
			&i.RowsPerSecond,
			&i.EventsPerSecond,
			&i.P95LatencyNs,
			&i.PeakAllocBytes,
			&i.AllocsPerEvent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationErrors = `-- name: ListValidationErrors :many
SELECT id, job_id, line, symbol, type, message, created_at
FROM validation_errors
WHERE job_id = $1
ORDER BY line ASC, created_at ASC
`

func (q *Queries) ListValidationErrors(ctx context.Context, jobID string) ([]ValidationError, error) {
	rows, err := q.db.Query(ctx, listValidationErrors, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationError
	for rows.Next() {
		var i ValidationError
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Line,
			&i.Symbol,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventFileStats = `-- name: UpdateEventFileStats :one
UPDATE event_files
SET sha256 = $2,
    rows = $3,
    bytes = $4
WHERE id = $1
RETURNING id, dataset_id, path, format, symbol, bytes, created_at, sha256, rows
`

type UpdateEventFileStatsParams struct {
	ID     string `json:"id"`
	Sha256 string `json:"sha256"`
	Rows   int64  `json:"rows"`
	Bytes  int64  `json:"bytes"`
}

func (q *Queries) UpdateEventFileStats(ctx context.Context, arg UpdateEventFileStatsParams) (EventFile, error) {
	row := q.db.QueryRow(ctx, updateEventFileStats,
		arg.ID,
		arg.Sha256,
		arg.Rows,
		arg.Bytes,
	)
	var i EventFile
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.Path,
		&i.Format,
		&i.Symbol,
		&i.Bytes,
		&i.CreatedAt,
		&i.Sha256,
		&i.Rows,
	)
	return i, err
}

const updateReplayCheckpoint = `-- name: UpdateReplayCheckpoint :execrows
UPDATE replay_jobs
SET checkpoint_line = GREATEST(checkpoint_line, $2)
WHERE id = $1
`

type UpdateReplayCheckpointParams struct {
	ID             string `json:"id"`
	CheckpointLine int64  `json:"checkpoint_line"`
}

func (q *Queries) UpdateReplayCheckpoint(ctx context.Context, arg UpdateReplayCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReplayCheckpoint, arg.ID, arg.CheckpointLine)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReplayJobStatus = `-- name: UpdateReplayJobStatus :one
UPDATE replay_jobs
SET status = $2,
    last_error = $3,
    attempts = attempts + 1,
    started_at = CASE WHEN $2 = 'running' THEN $4 ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'dlq') THEN $4 ELSE completed_at END,
    canceled_at = CASE WHEN $2 = 'canceled' THEN $4 ELSE canceled_at END
WHERE id = $1
RETURNING id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
`

type UpdateReplayJobStatusParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	LastError string             `json:"last_error"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

type UpdateReplayJobStatusRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) UpdateReplayJobStatus(ctx context.Context, arg UpdateReplayJobStatusParams) (UpdateReplayJobStatusRow, error) {
	row := q.db.QueryRow(ctx, updateReplayJobStatus,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.StartedAt,
	)
	var i UpdateReplayJobStatusRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}

const updateReplayManifest = `-- name: UpdateReplayManifest :one
UPDATE replay_jobs
SET manifest = $2
WHERE id = $1
RETURNING id, dataset_id, event_file_id, COALESCE(idempotency_key, '') AS idempotency_key,
    symbol, speed, status, attempts, last_error, checkpoint_line, created_at,
    started_at, completed_at, canceled_at, manifest
`

type UpdateReplayManifestParams struct {
	ID       string `json:"id"`
	Manifest []byte `json:"manifest"`
}

type UpdateReplayManifestRow struct {
	ID             string             `json:"id"`
	DatasetID      string             `json:"dataset_id"`
	EventFileID    string             `json:"event_file_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Symbol         string             `json:"symbol"`
	Speed          string             `json:"speed"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastError      string             `json:"last_error"`
	CheckpointLine int64              `json:"checkpoint_line"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	Manifest       []byte             `json:"manifest"`
}

func (q *Queries) UpdateReplayManifest(ctx context.Context, arg UpdateReplayManifestParams) (UpdateReplayManifestRow, error) {
	row := q.db.QueryRow(ctx, updateReplayManifest, arg.ID, arg.Manifest)
	var i UpdateReplayManifestRow
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.EventFileID,
		&i.IdempotencyKey,
		&i.Symbol,
		&i.Speed,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CheckpointLine,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.Manifest,
	)
	return i, err
}
