// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelReplayJob(ctx context.Context, arg CancelReplayJobParams) (CancelReplayJobRow, error)
	CompleteReplayJobStatus(ctx context.Context, arg CompleteReplayJobStatusParams) (int64, error)
	CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error)
	CreateEventFile(ctx context.Context, arg CreateEventFileParams) (EventFile, error)
	CreateReplayJob(ctx context.Context, arg CreateReplayJobParams) (CreateReplayJobRow, error)
	CreateReplayMetric(ctx context.Context, arg CreateReplayMetricParams) (ReplayMetric, error)
	CreateValidationError(ctx context.Context, arg CreateValidationErrorParams) (ValidationError, error)
	GetDataset(ctx context.Context, id string) (Dataset, error)
	GetEventFile(ctx context.Context, id string) (EventFile, error)
	GetReplayJob(ctx context.Context, id string) (GetReplayJobRow, error)
	GetReplayJobByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (GetReplayJobByIdempotencyKeyRow, error)
	ListDatasets(ctx context.Context) ([]Dataset, error)
	ListEventFiles(ctx context.Context, datasetID string) ([]EventFile, error)
	ListReplayJobs(ctx context.Context) ([]ListReplayJobsRow, error)
	ListReplayMetrics(ctx context.Context, jobID string) ([]ReplayMetric, error)
	ListValidationErrors(ctx context.Context, jobID string) ([]ValidationError, error)
	UpdateEventFileStats(ctx context.Context, arg UpdateEventFileStatsParams) (EventFile, error)
	UpdateReplayCheckpoint(ctx context.Context, arg UpdateReplayCheckpointParams) (int64, error)
	UpdateReplayJobStatus(ctx context.Context, arg UpdateReplayJobStatusParams) (UpdateReplayJobStatusRow, error)
	UpdateReplayManifest(ctx context.Context, arg UpdateReplayManifestParams) (UpdateReplayManifestRow, error)
}

var _ Querier = (*Queries)(nil)
